spring.application.name=vol1

server.servlet.context-path=/

# -------------------------------------------------------
# В Railway эти переменные подставляются автоматически
# -------------------------------------------------------
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/autosite}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:karate123}

# Hibernate создаёт таблицы автоматически по entities
# Поменяйте на 'validate' после первого запуска
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}


spring.thymeleaf.cache=false